
function decode_RFC_7541_Appendix_B : boolean;
{ this source code was generated by Oc Rev. 1.254 }
{ Oc --huff C:\Users\Andreas\Documents\Embarcadero\Studio\Projekte\OrgaMon-FS\Oc\huffman\HPACK\RFC_7541_Appendix_B.huff }
{ 20170124 11:49:19 }
begin
 result := false;
 while (Octets>0) do
 begin
  if B then
  begin { 1 }
   if B then
   begin { 11 }
    if B then
    begin { 111 }
     if B then
     begin { 1111 }
      if B then
      begin { 11111 }
       if B then
       begin { 111111 }
        if B then
        begin { 1111111 }
         if B then
         begin { 11111111 }
          if B then
          begin { 111111111 }
           if B then
           begin { 1111111111 }
            if B then
            begin { 11111111111 }
             if B then
             begin { 111111111111 }
              if B then
              begin { 1111111111111 }
               if B then
               begin { 11111111111111 }
                if B then
                begin { 111111111111111 }
                 if B then
                 begin { 1111111111111111 }
                  if B then
                  begin { 11111111111111111 }
                   if B then
                   begin { 111111111111111111 }
                    if B then
                    begin { 1111111111111111111 }
                     if B then
                     begin { 11111111111111111111 }
                      if B then
                      begin { 111111111111111111111 }
                       if B then
                       begin { 1111111111111111111111 }
                        if B then
                        begin { 11111111111111111111111 }
                         if B then
                         begin { 111111111111111111111111 }
                          if B then
                          begin { 1111111111111111111111111 }
                           if B then
                           begin { 11111111111111111111111111 }
                            if B then
                            begin { 111111111111111111111111111 }
                             if B then
                             begin { 1111111111111111111111111111 }
                              if B then
                              begin { 11111111111111111111111111111 }
                               if B then
                               begin { 111111111111111111111111111111 }
                                result := true;
                                break;
                               end else
                               begin { 111111111111111111111111111110 }
                                sym(22);
                               end;
                              end else
                              begin { 11111111111111111111111111110 }
                               if B then
                               begin { 111111111111111111111111111101 }
                                sym(13);
                               end else
                               begin { 111111111111111111111111111100 }
                                sym(10);
                               end;
                              end;
                             end else
                             begin { 1111111111111111111111111110 }
                              sym(249);
                             end;
                            end else
                            begin { 111111111111111111111111110 }
                             if B then
                             begin { 1111111111111111111111111101 }
                              sym(220);
                             end else
                             begin { 1111111111111111111111111100 }
                              sym(127);
                             end;
                            end;
                           end else
                           begin { 11111111111111111111111110 }
                            if B then
                            begin { 111111111111111111111111101 }
                             if B then
                             begin { 1111111111111111111111111011 }
                              sym(31);
                             end else
                             begin { 1111111111111111111111111010 }
                              sym(30);
                             end;
                            end else
                            begin { 111111111111111111111111100 }
                             if B then
                             begin { 1111111111111111111111111001 }
                              sym(29);
                             end else
                             begin { 1111111111111111111111111000 }
                              sym(28);
                             end;
                            end;
                           end;
                          end else
                          begin { 1111111111111111111111110 }
                           if B then
                           begin { 11111111111111111111111101 }
                            if B then
                            begin { 111111111111111111111111011 }
                             if B then
                             begin { 1111111111111111111111110111 }
                              sym(27);
                             end else
                             begin { 1111111111111111111111110110 }
                              sym(26);
                             end;
                            end else
                            begin { 111111111111111111111111010 }
                             if B then
                             begin { 1111111111111111111111110101 }
                              sym(25);
                             end else
                             begin { 1111111111111111111111110100 }
                              sym(24);
                             end;
                            end;
                           end else
                           begin { 11111111111111111111111100 }
                            if B then
                            begin { 111111111111111111111111001 }
                             if B then
                             begin { 1111111111111111111111110011 }
                              sym(23);
                             end else
                             begin { 1111111111111111111111110010 }
                              sym(21);
                             end;
                            end else
                            begin { 111111111111111111111111000 }
                             if B then
                             begin { 1111111111111111111111110001 }
                              sym(20);
                             end else
                             begin { 1111111111111111111111110000 }
                              sym(19);
                             end;
                            end;
                           end;
                          end;
                         end else
                         begin { 111111111111111111111110 }
                          if B then
                          begin { 1111111111111111111111101 }
                           if B then
                           begin { 11111111111111111111111011 }
                            if B then
                            begin { 111111111111111111111110111 }
                             if B then
                             begin { 1111111111111111111111101111 }
                              sym(18);
                             end else
                             begin { 1111111111111111111111101110 }
                              sym(17);
                             end;
                            end else
                            begin { 111111111111111111111110110 }
                             if B then
                             begin { 1111111111111111111111101101 }
                              sym(16);
                             end else
                             begin { 1111111111111111111111101100 }
                              sym(15);
                             end;
                            end;
                           end else
                           begin { 11111111111111111111111010 }
                            if B then
                            begin { 111111111111111111111110101 }
                             if B then
                             begin { 1111111111111111111111101011 }
                              sym(14);
                             end else
                             begin { 1111111111111111111111101010 }
                              sym(12);
                             end;
                            end else
                            begin { 111111111111111111111110100 }
                             if B then
                             begin { 1111111111111111111111101001 }
                              sym(11);
                             end else
                             begin { 1111111111111111111111101000 }
                              sym(8);
                             end;
                            end;
                           end;
                          end else
                          begin { 1111111111111111111111100 }
                           if B then
                           begin { 11111111111111111111111001 }
                            if B then
                            begin { 111111111111111111111110011 }
                             if B then
                             begin { 1111111111111111111111100111 }
                              sym(7);
                             end else
                             begin { 1111111111111111111111100110 }
                              sym(6);
                             end;
                            end else
                            begin { 111111111111111111111110010 }
                             if B then
                             begin { 1111111111111111111111100101 }
                              sym(5);
                             end else
                             begin { 1111111111111111111111100100 }
                              sym(4);
                             end;
                            end;
                           end else
                           begin { 11111111111111111111111000 }
                            if B then
                            begin { 111111111111111111111110001 }
                             if B then
                             begin { 1111111111111111111111100011 }
                              sym(3);
                             end else
                             begin { 1111111111111111111111100010 }
                              sym(2);
                             end;
                            end else
                            begin { 111111111111111111111110000 }
                             sym(254);
                            end;
                           end;
                          end;
                         end;
                        end else
                        begin { 11111111111111111111110 }
                         if B then
                         begin { 111111111111111111111101 }
                          if B then
                          begin { 1111111111111111111111011 }
                           if B then
                           begin { 11111111111111111111110111 }
                            if B then
                            begin { 111111111111111111111101111 }
                             sym(253);
                            end else
                            begin { 111111111111111111111101110 }
                             sym(252);
                            end;
                           end else
                           begin { 11111111111111111111110110 }
                            if B then
                            begin { 111111111111111111111101101 }
                             sym(251);
                            end else
                            begin { 111111111111111111111101100 }
                             sym(250);
                            end;
                           end;
                          end else
                          begin { 1111111111111111111111010 }
                           if B then
                           begin { 11111111111111111111110101 }
                            if B then
                            begin { 111111111111111111111101011 }
                             sym(248);
                            end else
                            begin { 111111111111111111111101010 }
                             sym(247);
                            end;
                           end else
                           begin { 11111111111111111111110100 }
                            if B then
                            begin { 111111111111111111111101001 }
                             sym(246);
                            end else
                            begin { 111111111111111111111101000 }
                             sym(245);
                            end;
                           end;
                          end;
                         end else
                         begin { 111111111111111111111100 }
                          if B then
                          begin { 1111111111111111111111001 }
                           if B then
                           begin { 11111111111111111111110011 }
                            if B then
                            begin { 111111111111111111111100111 }
                             sym(244);
                            end else
                            begin { 111111111111111111111100110 }
                             sym(241);
                            end;
                           end else
                           begin { 11111111111111111111110010 }
                            if B then
                            begin { 111111111111111111111100101 }
                             sym(223);
                            end else
                            begin { 111111111111111111111100100 }
                             sym(222);
                            end;
                           end;
                          end else
                          begin { 1111111111111111111111000 }
                           if B then
                           begin { 11111111111111111111110001 }
                            if B then
                            begin { 111111111111111111111100011 }
                             sym(221);
                            end else
                            begin { 111111111111111111111100010 }
                             sym(214);
                            end;
                           end else
                           begin { 11111111111111111111110000 }
                            if B then
                            begin { 111111111111111111111100001 }
                             sym(212);
                            end else
                            begin { 111111111111111111111100000 }
                             sym(211);
                            end;
                           end;
                          end;
                         end;
                        end;
                       end else
                       begin { 1111111111111111111110 }
                        if B then
                        begin { 11111111111111111111101 }
                         if B then
                         begin { 111111111111111111111011 }
                          if B then
                          begin { 1111111111111111111110111 }
                           if B then
                           begin { 11111111111111111111101111 }
                            if B then
                            begin { 111111111111111111111011111 }
                             sym(204);
                            end else
                            begin { 111111111111111111111011110 }
                             sym(203);
                            end;
                           end else
                           begin { 11111111111111111111101110 }
                            sym(255);
                           end;
                          end else
                          begin { 1111111111111111111110110 }
                           if B then
                           begin { 11111111111111111111101101 }
                            sym(243);
                           end else
                           begin { 11111111111111111111101100 }
                            sym(242);
                           end;
                          end;
                         end else
                         begin { 111111111111111111111010 }
                          if B then
                          begin { 1111111111111111111110101 }
                           if B then
                           begin { 11111111111111111111101011 }
                            sym(240);
                           end else
                           begin { 11111111111111111111101010 }
                            sym(238);
                           end;
                          end else
                          begin { 1111111111111111111110100 }
                           if B then
                           begin { 11111111111111111111101001 }
                            sym(219);
                           end else
                           begin { 11111111111111111111101000 }
                            sym(218);
                           end;
                          end;
                         end;
                        end else
                        begin { 11111111111111111111100 }
                         if B then
                         begin { 111111111111111111111001 }
                          if B then
                          begin { 1111111111111111111110011 }
                           if B then
                           begin { 11111111111111111111100111 }
                            sym(213);
                           end else
                           begin { 11111111111111111111100110 }
                            sym(210);
                           end;
                          end else
                          begin { 1111111111111111111110010 }
                           if B then
                           begin { 11111111111111111111100101 }
                            sym(205);
                           end else
                           begin { 11111111111111111111100100 }
                            sym(202);
                           end;
                          end;
                         end else
                         begin { 111111111111111111111000 }
                          if B then
                          begin { 1111111111111111111110001 }
                           if B then
                           begin { 11111111111111111111100011 }
                            sym(201);
                           end else
                           begin { 11111111111111111111100010 }
                            sym(200);
                           end;
                          end else
                          begin { 1111111111111111111110000 }
                           if B then
                           begin { 11111111111111111111100001 }
                            sym(193);
                           end else
                           begin { 11111111111111111111100000 }
                            sym(192);
                           end;
                          end;
                         end;
                        end;
                       end;
                      end else
                      begin { 111111111111111111110 }
                       if B then
                       begin { 1111111111111111111101 }
                        if B then
                        begin { 11111111111111111111011 }
                         if B then
                         begin { 111111111111111111110111 }
                          if B then
                          begin { 1111111111111111111101111 }
                           sym(235);
                          end else
                          begin { 1111111111111111111101110 }
                           sym(234);
                          end;
                         end else
                         begin { 111111111111111111110110 }
                          if B then
                          begin { 1111111111111111111101101 }
                           sym(207);
                          end else
                          begin { 1111111111111111111101100 }
                           sym(199);
                          end;
                         end;
                        end else
                        begin { 11111111111111111111010 }
                         if B then
                         begin { 111111111111111111110101 }
                          sym(237);
                         end else
                         begin { 111111111111111111110100 }
                          sym(236);
                         end;
                        end;
                       end else
                       begin { 1111111111111111111100 }
                        if B then
                        begin { 11111111111111111111001 }
                         if B then
                         begin { 111111111111111111110011 }
                          sym(225);
                         end else
                         begin { 111111111111111111110010 }
                          sym(215);
                         end;
                        end else
                        begin { 11111111111111111111000 }
                         if B then
                         begin { 111111111111111111110001 }
                          sym(206);
                         end else
                         begin { 111111111111111111110000 }
                          sym(171);
                         end;
                        end;
                       end;
                      end;
                     end else
                     begin { 11111111111111111110 }
                      if B then
                      begin { 111111111111111111101 }
                       if B then
                       begin { 1111111111111111111011 }
                        if B then
                        begin { 11111111111111111110111 }
                         if B then
                         begin { 111111111111111111101111 }
                          sym(159);
                         end else
                         begin { 111111111111111111101110 }
                          sym(148);
                         end;
                        end else
                        begin { 11111111111111111110110 }
                         if B then
                         begin { 111111111111111111101101 }
                          sym(145);
                         end else
                         begin { 111111111111111111101100 }
                          sym(144);
                         end;
                        end;
                       end else
                       begin { 1111111111111111111010 }
                        if B then
                        begin { 11111111111111111110101 }
                         if B then
                         begin { 111111111111111111101011 }
                          sym(142);
                         end else
                         begin { 111111111111111111101010 }
                          sym(9);
                         end;
                        end else
                        begin { 11111111111111111110100 }
                         sym(239);
                        end;
                       end;
                      end else
                      begin { 111111111111111111100 }
                       if B then
                       begin { 1111111111111111111001 }
                        if B then
                        begin { 11111111111111111110011 }
                         sym(231);
                        end else
                        begin { 11111111111111111110010 }
                         sym(197);
                        end;
                       end else
                       begin { 1111111111111111111000 }
                        if B then
                        begin { 11111111111111111110001 }
                         sym(191);
                        end else
                        begin { 11111111111111111110000 }
                         sym(188);
                        end;
                       end;
                      end;
                     end;
                    end else
                    begin { 1111111111111111110 }
                     if B then
                     begin { 11111111111111111101 }
                      if B then
                      begin { 111111111111111111011 }
                       if B then
                       begin { 1111111111111111110111 }
                        if B then
                        begin { 11111111111111111101111 }
                         sym(183);
                        end else
                        begin { 11111111111111111101110 }
                         sym(182);
                        end;
                       end else
                       begin { 1111111111111111110110 }
                        if B then
                        begin { 11111111111111111101101 }
                         sym(180);
                        end else
                        begin { 11111111111111111101100 }
                         sym(175);
                        end;
                       end;
                      end else
                      begin { 111111111111111111010 }
                       if B then
                       begin { 1111111111111111110101 }
                        if B then
                        begin { 11111111111111111101011 }
                         sym(174);
                        end else
                        begin { 11111111111111111101010 }
                         sym(168);
                        end;
                       end else
                       begin { 1111111111111111110100 }
                        if B then
                        begin { 11111111111111111101001 }
                         sym(166);
                        end else
                        begin { 11111111111111111101000 }
                         sym(165);
                        end;
                       end;
                      end;
                     end else
                     begin { 11111111111111111100 }
                      if B then
                      begin { 111111111111111111001 }
                       if B then
                       begin { 1111111111111111110011 }
                        if B then
                        begin { 11111111111111111100111 }
                         sym(158);
                        end else
                        begin { 11111111111111111100110 }
                         sym(157);
                        end;
                       end else
                       begin { 1111111111111111110010 }
                        if B then
                        begin { 11111111111111111100101 }
                         sym(155);
                        end else
                        begin { 11111111111111111100100 }
                         sym(152);
                        end;
                       end;
                      end else
                      begin { 111111111111111111000 }
                       if B then
                       begin { 1111111111111111110001 }
                        if B then
                        begin { 11111111111111111100011 }
                         sym(151);
                        end else
                        begin { 11111111111111111100010 }
                         sym(150);
                        end;
                       end else
                       begin { 1111111111111111110000 }
                        if B then
                        begin { 11111111111111111100001 }
                         sym(149);
                        end else
                        begin { 11111111111111111100000 }
                         sym(147);
                        end;
                       end;
                      end;
                     end;
                    end;
                   end else
                   begin { 111111111111111110 }
                    if B then
                    begin { 1111111111111111101 }
                     if B then
                     begin { 11111111111111111011 }
                      if B then
                      begin { 111111111111111110111 }
                       if B then
                       begin { 1111111111111111101111 }
                        if B then
                        begin { 11111111111111111011111 }
                         sym(143);
                        end else
                        begin { 11111111111111111011110 }
                         sym(141);
                        end;
                       end else
                       begin { 1111111111111111101110 }
                        if B then
                        begin { 11111111111111111011101 }
                         sym(140);
                        end else
                        begin { 11111111111111111011100 }
                         sym(139);
                        end;
                       end;
                      end else
                      begin { 111111111111111110110 }
                       if B then
                       begin { 1111111111111111101101 }
                        if B then
                        begin { 11111111111111111011011 }
                         sym(138);
                        end else
                        begin { 11111111111111111011010 }
                         sym(137);
                        end;
                       end else
                       begin { 1111111111111111101100 }
                        if B then
                        begin { 11111111111111111011001 }
                         sym(135);
                        end else
                        begin { 11111111111111111011000 }
                         sym(1);
                        end;
                       end;
                      end;
                     end else
                     begin { 11111111111111111010 }
                      if B then
                      begin { 111111111111111110101 }
                       if B then
                       begin { 1111111111111111101011 }
                        sym(233);
                       end else
                       begin { 1111111111111111101010 }
                        sym(232);
                       end;
                      end else
                      begin { 111111111111111110100 }
                       if B then
                       begin { 1111111111111111101001 }
                        sym(228);
                       end else
                       begin { 1111111111111111101000 }
                        sym(198);
                       end;
                      end;
                     end;
                    end else
                    begin { 1111111111111111100 }
                     if B then
                     begin { 11111111111111111001 }
                      if B then
                      begin { 111111111111111110011 }
                       if B then
                       begin { 1111111111111111100111 }
                        sym(196);
                       end else
                       begin { 1111111111111111100110 }
                        sym(190);
                       end;
                      end else
                      begin { 111111111111111110010 }
                       if B then
                       begin { 1111111111111111100101 }
                        sym(189);
                       end else
                       begin { 1111111111111111100100 }
                        sym(187);
                       end;
                      end;
                     end else
                     begin { 11111111111111111000 }
                      if B then
                      begin { 111111111111111110001 }
                       if B then
                       begin { 1111111111111111100011 }
                        sym(186);
                       end else
                       begin { 1111111111111111100010 }
                        sym(185);
                       end;
                      end else
                      begin { 111111111111111110000 }
                       if B then
                       begin { 1111111111111111100001 }
                        sym(181);
                       end else
                       begin { 1111111111111111100000 }
                        sym(178);
                       end;
                      end;
                     end;
                    end;
                   end;
                  end else
                  begin { 11111111111111110 }
                   if B then
                   begin { 111111111111111101 }
                    if B then
                    begin { 1111111111111111011 }
                     if B then
                     begin { 11111111111111110111 }
                      if B then
                      begin { 111111111111111101111 }
                       if B then
                       begin { 1111111111111111011111 }
                        sym(173);
                       end else
                       begin { 1111111111111111011110 }
                        sym(170);
                       end;
                      end else
                      begin { 111111111111111101110 }
                       if B then
                       begin { 1111111111111111011101 }
                        sym(169);
                       end else
                       begin { 1111111111111111011100 }
                        sym(164);
                       end;
                      end;
                     end else
                     begin { 11111111111111110110 }
                      if B then
                      begin { 111111111111111101101 }
                       if B then
                       begin { 1111111111111111011011 }
                        sym(163);
                       end else
                       begin { 1111111111111111011010 }
                        sym(160);
                       end;
                      end else
                      begin { 111111111111111101100 }
                       if B then
                       begin { 1111111111111111011001 }
                        sym(156);
                       end else
                       begin { 1111111111111111011000 }
                        sym(154);
                       end;
                      end;
                     end;
                    end else
                    begin { 1111111111111111010 }
                     if B then
                     begin { 11111111111111110101 }
                      if B then
                      begin { 111111111111111101011 }
                       if B then
                       begin { 1111111111111111010111 }
                        sym(146);
                       end else
                       begin { 1111111111111111010110 }
                        sym(136);
                       end;
                      end else
                      begin { 111111111111111101010 }
                       if B then
                       begin { 1111111111111111010101 }
                        sym(134);
                       end else
                       begin { 1111111111111111010100 }
                        sym(133);
                       end;
                      end;
                     end else
                     begin { 11111111111111110100 }
                      if B then
                      begin { 111111111111111101001 }
                       if B then
                       begin { 1111111111111111010011 }
                        sym(132);
                       end else
                       begin { 1111111111111111010010 }
                        sym(129);
                       end;
                      end else
                      begin { 111111111111111101000 }
                       sym(230);
                      end;
                     end;
                    end;
                   end else
                   begin { 111111111111111100 }
                    if B then
                    begin { 1111111111111111001 }
                     if B then
                     begin { 11111111111111110011 }
                      if B then
                      begin { 111111111111111100111 }
                       sym(229);
                      end else
                      begin { 111111111111111100110 }
                       sym(227);
                      end;
                     end else
                     begin { 11111111111111110010 }
                      if B then
                      begin { 111111111111111100101 }
                       sym(217);
                      end else
                      begin { 111111111111111100100 }
                       sym(216);
                      end;
                     end;
                    end else
                    begin { 1111111111111111000 }
                     if B then
                     begin { 11111111111111110001 }
                      if B then
                      begin { 111111111111111100011 }
                       sym(209);
                      end else
                      begin { 111111111111111100010 }
                       sym(179);
                      end;
                     end else
                     begin { 11111111111111110000 }
                      if B then
                      begin { 111111111111111100001 }
                       sym(177);
                      end else
                      begin { 111111111111111100000 }
                       sym(176);
                      end;
                     end;
                    end;
                   end;
                  end;
                 end else
                 begin { 1111111111111110 }
                  if B then
                  begin { 11111111111111101 }
                   if B then
                   begin { 111111111111111011 }
                    if B then
                    begin { 1111111111111110111 }
                     if B then
                     begin { 11111111111111101111 }
                      if B then
                      begin { 111111111111111011111 }
                       sym(172);
                      end else
                      begin { 111111111111111011110 }
                       sym(167);
                      end;
                     end else
                     begin { 11111111111111101110 }
                      if B then
                      begin { 111111111111111011101 }
                       sym(161);
                      end else
                      begin { 111111111111111011100 }
                       sym(153);
                      end;
                     end;
                    end else
                    begin { 1111111111111110110 }
                     if B then
                     begin { 11111111111111101101 }
                      sym(226);
                     end else
                     begin { 11111111111111101100 }
                      sym(224);
                     end;
                    end;
                   end else
                   begin { 111111111111111010 }
                    if B then
                    begin { 1111111111111110101 }
                     if B then
                     begin { 11111111111111101011 }
                      sym(194);
                     end else
                     begin { 11111111111111101010 }
                      sym(184);
                     end;
                    end else
                    begin { 1111111111111110100 }
                     if B then
                     begin { 11111111111111101001 }
                      sym(162);
                     end else
                     begin { 11111111111111101000 }
                      sym(131);
                     end;
                    end;
                   end;
                  end else
                  begin { 11111111111111100 }
                   if B then
                   begin { 111111111111111001 }
                    if B then
                    begin { 1111111111111110011 }
                     if B then
                     begin { 11111111111111100111 }
                      sym(130);
                     end else
                     begin { 11111111111111100110 }
                      sym(128);
                     end;
                    end else
                    begin { 1111111111111110010 }
                     sym(208);
                    end;
                   end else
                   begin { 111111111111111000 }
                    if B then
                    begin { 1111111111111110001 }
                     sym(195);
                    end else
                    begin { 1111111111111110000 }
                     sym(92);
                    end;
                   end;
                  end;
                 end;
                end else
                begin { 111111111111110 }
                 sym(123);
                end;
               end else
               begin { 11111111111110 }
                if B then
                begin { 111111111111101 }
                 sym(96);
                end else
                begin { 111111111111100 }
                 sym(60);
                end;
               end;
              end else
              begin { 1111111111110 }
               if B then
               begin { 11111111111101 }
                sym(125);
               end else
               begin { 11111111111100 }
                sym(94);
               end;
              end;
             end else
             begin { 111111111110 }
              if B then
              begin { 1111111111101 }
               sym(126);
              end else
              begin { 1111111111100 }
               sym(93);
              end;
             end;
            end else
            begin { 11111111110 }
             if B then
             begin { 111111111101 }
              if B then
              begin { 1111111111011 }
               sym(91);
              end else
              begin { 1111111111010 }
               sym(64);
              end;
             end else
             begin { 111111111100 }
              if B then
              begin { 1111111111001 }
               sym(36);
              end else
              begin { 1111111111000 }
               sym(0);
              end;
             end;
            end;
           end else
           begin { 1111111110 }
            if B then
            begin { 11111111101 }
             if B then
             begin { 111111111011 }
              sym(62);
             end else
             begin { 111111111010 }
              sym(35);
             end;
            end else
            begin { 11111111100 }
             sym(124);
            end;
           end;
          end else
          begin { 111111110 }
           if B then
           begin { 1111111101 }
            if B then
            begin { 11111111011 }
             sym(43);
            end else
            begin { 11111111010 }
             sym(39);
            end;
           end else
           begin { 1111111100 }
            sym(63);
           end;
          end;
         end else
         begin { 11111110 }
          if B then
          begin { 111111101 }
           if B then
           begin { 1111111011 }
            sym(41);
           end else
           begin { 1111111010 }
            sym(40);
           end;
          end else
          begin { 111111100 }
           if B then
           begin { 1111111001 }
            sym(34);
           end else
           begin { 1111111000 }
            sym(33);
           end;
          end;
         end;
        end else
        begin { 1111110 }
         if B then
         begin { 11111101 }
          sym(90);
         end else
         begin { 11111100 }
          sym(88);
         end;
        end;
       end else
       begin { 111110 }
        if B then
        begin { 1111101 }
         if B then
         begin { 11111011 }
          sym(59);
         end else
         begin { 11111010 }
          sym(44);
         end;
        end else
        begin { 1111100 }
         if B then
         begin { 11111001 }
          sym(42);
         end else
         begin { 11111000 }
          sym(38);
         end;
        end;
       end;
      end else
      begin { 11110 }
       if B then
       begin { 111101 }
        if B then
        begin { 1111011 }
         sym(122);
        end else
        begin { 1111010 }
         sym(121);
        end;
       end else
       begin { 111100 }
        if B then
        begin { 1111001 }
         sym(120);
        end else
        begin { 1111000 }
         sym(119);
        end;
       end;
      end;
     end else
     begin { 1110 }
      if B then
      begin { 11101 }
       if B then
       begin { 111011 }
        if B then
        begin { 1110111 }
         sym(118);
        end else
        begin { 1110110 }
         sym(113);
        end;
       end else
       begin { 111010 }
        if B then
        begin { 1110101 }
         sym(107);
        end else
        begin { 1110100 }
         sym(106);
        end;
       end;
      end else
      begin { 11100 }
       if B then
       begin { 111001 }
        if B then
        begin { 1110011 }
         sym(89);
        end else
        begin { 1110010 }
         sym(87);
        end;
       end else
       begin { 111000 }
        if B then
        begin { 1110001 }
         sym(86);
        end else
        begin { 1110000 }
         sym(85);
        end;
       end;
      end;
     end;
    end else
    begin { 110 }
     if B then
     begin { 1101 }
      if B then
      begin { 11011 }
       if B then
       begin { 110111 }
        if B then
        begin { 1101111 }
         sym(84);
        end else
        begin { 1101110 }
         sym(83);
        end;
       end else
       begin { 110110 }
        if B then
        begin { 1101101 }
         sym(82);
        end else
        begin { 1101100 }
         sym(81);
        end;
       end;
      end else
      begin { 11010 }
       if B then
       begin { 110101 }
        if B then
        begin { 1101011 }
         sym(80);
        end else
        begin { 1101010 }
         sym(79);
        end;
       end else
       begin { 110100 }
        if B then
        begin { 1101001 }
         sym(78);
        end else
        begin { 1101000 }
         sym(77);
        end;
       end;
      end;
     end else
     begin { 1100 }
      if B then
      begin { 11001 }
       if B then
       begin { 110011 }
        if B then
        begin { 1100111 }
         sym(76);
        end else
        begin { 1100110 }
         sym(75);
        end;
       end else
       begin { 110010 }
        if B then
        begin { 1100101 }
         sym(74);
        end else
        begin { 1100100 }
         sym(73);
        end;
       end;
      end else
      begin { 11000 }
       if B then
       begin { 110001 }
        if B then
        begin { 1100011 }
         sym(72);
        end else
        begin { 1100010 }
         sym(71);
        end;
       end else
       begin { 110000 }
        if B then
        begin { 1100001 }
         sym(70);
        end else
        begin { 1100000 }
         sym(69);
        end;
       end;
      end;
     end;
    end;
   end else
   begin { 10 }
    if B then
    begin { 101 }
     if B then
     begin { 1011 }
      if B then
      begin { 10111 }
       if B then
       begin { 101111 }
        if B then
        begin { 1011111 }
         sym(68);
        end else
        begin { 1011110 }
         sym(67);
        end;
       end else
       begin { 101110 }
        if B then
        begin { 1011101 }
         sym(66);
        end else
        begin { 1011100 }
         sym(58);
        end;
       end;
      end else
      begin { 10110 }
       if B then
       begin { 101101 }
        sym(117);
       end else
       begin { 101100 }
        sym(114);
       end;
      end;
     end else
     begin { 1010 }
      if B then
      begin { 10101 }
       if B then
       begin { 101011 }
        sym(112);
       end else
       begin { 101010 }
        sym(110);
       end;
      end else
      begin { 10100 }
       if B then
       begin { 101001 }
        sym(109);
       end else
       begin { 101000 }
        sym(108);
       end;
      end;
     end;
    end else
    begin { 100 }
     if B then
     begin { 1001 }
      if B then
      begin { 10011 }
       if B then
       begin { 100111 }
        sym(104);
       end else
       begin { 100110 }
        sym(103);
       end;
      end else
      begin { 10010 }
       if B then
       begin { 100101 }
        sym(102);
       end else
       begin { 100100 }
        sym(100);
       end;
      end;
     end else
     begin { 1000 }
      if B then
      begin { 10001 }
       if B then
       begin { 100011 }
        sym(98);
       end else
       begin { 100010 }
        sym(95);
       end;
      end else
      begin { 10000 }
       if B then
       begin { 100001 }
        sym(65);
       end else
       begin { 100000 }
        sym(61);
       end;
      end;
     end;
    end;
   end;
  end else
  begin { 0 }
   if B then
   begin { 01 }
    if B then
    begin { 011 }
     if B then
     begin { 0111 }
      if B then
      begin { 01111 }
       if B then
       begin { 011111 }
        sym(57);
       end else
       begin { 011110 }
        sym(56);
       end;
      end else
      begin { 01110 }
       if B then
       begin { 011101 }
        sym(55);
       end else
       begin { 011100 }
        sym(54);
       end;
      end;
     end else
     begin { 0110 }
      if B then
      begin { 01101 }
       if B then
       begin { 011011 }
        sym(53);
       end else
       begin { 011010 }
        sym(52);
       end;
      end else
      begin { 01100 }
       if B then
       begin { 011001 }
        sym(51);
       end else
       begin { 011000 }
        sym(47);
       end;
      end;
     end;
    end else
    begin { 010 }
     if B then
     begin { 0101 }
      if B then
      begin { 01011 }
       if B then
       begin { 010111 }
        sym(46);
       end else
       begin { 010110 }
        sym(45);
       end;
      end else
      begin { 01010 }
       if B then
       begin { 010101 }
        sym(37);
       end else
       begin { 010100 }
        sym(32);
       end;
      end;
     end else
     begin { 0100 }
      if B then
      begin { 01001 }
       sym(116);
      end else
      begin { 01000 }
       sym(115);
      end;
     end;
    end;
   end else
   begin { 00 }
    if B then
    begin { 001 }
     if B then
     begin { 0011 }
      if B then
      begin { 00111 }
       sym(111);
      end else
      begin { 00110 }
       sym(105);
      end;
     end else
     begin { 0010 }
      if B then
      begin { 00101 }
       sym(101);
      end else
      begin { 00100 }
       sym(99);
      end;
     end;
    end else
    begin { 000 }
     if B then
     begin { 0001 }
      if B then
      begin { 00011 }
       sym(97);
      end else
      begin { 00010 }
       sym(50);
      end;
     end else
     begin { 0000 }
      if B then
      begin { 00001 }
       sym(49);
      end else
      begin { 00000 }
       sym(48);
      end;
     end;
    end;
   end;
  end;
 end;
end;
